// ==UserScript==
// @id             Ad Auto Close Popup
// @name           Ad Auto Close Popup
// @namespace      Ad Auto Close Popup
// @description    Close Popups
// @copyright      @copyright 2020, ced (https://cedfer2.github.io/ex/)
// @version        1.0.0
// @license        BSD
// @homepageURL    https://cedfer2.github.io/ex/
// @supportURL     https://cedfer2.github.io/ex/issues
// @icon           https://cdn0.iconfinder.com/data/icons/ui-designer-and-creative-design/64/Popup-window-ui-512.png
// @supportURL     https://cedfer2.github.io/ex/
// @contributionURL https://cedfer2.github.io/ex/
// @include       *.caliente.mx/*
// @include       *contehos.com/*
// @include       *syndication.optimizesrv.com/*
// @include       *powhyptene.pro/*
// @include       *ampugi334f.com/*
// @include       *p6p2w3v92czo.com/*
// @include       *greatdexchange.com/*
// @include       *cjf25jklrwqt.com/*
// @include       *promo.codere.mx/*
// @include       *push.aarth.net/*
// @include       *hooify.com/*
// @include       *popcornlinks.com/*
// @include       *nerve.eshkol.io/*
// @include       *rotumal.com/*
// @include       *p377843.infopicked.com/*
// @include       *serve.popads.net/*
// @include       *totogetica.com/*
// @include       *hentaiplaytime.com/*
// @include       *upvid.host/*
// @include       *ver.acceder.gratis/*
// @include       *signup.musicmaddness.net/*
// @include       *kiyzb.27823.club/*
// @include       *tczzzlwpss.com/*
// @include       *clkn.browserg.com/*
// @include       *mys.myservdir.com/*
// @include       *kiyzb.27823.club.com/*
// @include       *eu.dspmulti.com/*
// @include       *megdexchange.com/*
// @include       *kyzb.27823.club/*
// @include       *engine.spotscenered.info/*
// @include       *start.virtualwordsland.com/*
// @include       *lichtpass.com/*
// @include       *start.virtualworldsland.com/*
// @include       *chaglihysty.pro/*
// @include       *worldofwarships.com/*
// @include       *oyi9f1kbaj.com/*
// @include       *eu.dsmuilti.com/*
// @include       *chaglihsty.pro/*
// @include       *0yi9f1kbaj.com/*
// @include       *ebetoni.com/*
// @include       *1.press-to-allow.com/*
// @include       *.adbooth.com/*
// @include       *.adjuggler.net/*
// @include       *.axeso5.com/*
// @include       *.bebi.com/*
// @include       *.chatango.com/*
// @include       *.forgeofempires.com/*
// @include       *.goodgamestudios.com/*
// @include       *.jobego.com/*
// @include       *.miramagia.com/*
// @include       *.r2games.com/*
// @include       *tara-videncia.com/*
// @include       *.secureintl.com/?sov=*
// @include       *.sharestiforp.com/*
// @include       *.adviddkxh.com/*
// @include       *7.rotator.wigetmedia.com/*
// @include       *90secondsqueezepage.com/*
// @include       *ad.xtendmedia.com/*
// @include       *ar.flirchi.com/*
// @include       *adtgs.com/*
// @include       *autoresponderprofitsystem.com/*
// @include       *besthdwallpaperstock.net/*
// @include       *blogrentable.ws/*
// @include       *bidtrk.com/*
// @include       *browsergame.travian.cl/*
// @include       *channel-survey-center.com/*
// @include       *channel-reward-central.com/*
// @include       *citytorate.com/*
// @include       *citytorate.*
// @include       *cuenta.91.com/common*
// @include       *ccstreasuresngifts.com/*
// @include       *cpalead.com/*
// @include       *diabloheroes.com/*
// @include       *download-manage.com/*
// @include       *downloadcdn.filebulldog.com/*
// @include       *dylanjust.com/*
// @include       *engine.4dsply.com/*
// @include       *engine.adbooth.com/*
// @include       *f-sluts.net/*
// @include       *fbprizes.com/*
// @include       *gacetainformativa.com/*
// @include       *gamingwonderland.com/*
// @include       *googleads.g.doubleclick.net/*
// @include       *guiaconsumidor.com/*
// @include       *hfantasy.se/*
// @include       *ibuildapp.com/*
// @include       *ilquotidianoinclasse.corriere.it/*
// @include       *inclk.com/*
// @include       *ipad-winners/*
// @include       *ipad-winners.info/*
// @include       *landingpage.ar.toing.com.br/*
// @include       *lolhardonline.com/*
// @include       *meetsexygirls.org/*
// @include       *minus.com/*
// @include       *mlgame.es/*
// @include       *offer.myaax.com/*
// @include       *onlinesuccesswithchris.com/*
// @include       *plarium.com/*
// @include       *popads.net/*
// @include       *popmyads.com/*
// @include       *promoprizeland.com/*
// @include       *promorewardcenter.com/*
// @include       *truemediapipe.com/*
// @include       *ridoko.com/*
// @include       *x19network.com/*
// @include       *safedownloadsrus143.com/*
// @include       *startmyripple.com/*
// @include       *survey*center.com/*
// @include       *survey*center.net/*
// @include       *thebrowsergame.com/*
// @include       *videorewardspace.com/*
// @include       *virtual-dj.begin.pro/*
// @include       *your*central.com/*
// @include       *ad.*.com/*/ads/*
// @include       *ad.directrev.com/*
// @include       *ad.letsbonus.com/*
// @include       *ad.yieldmanager.com/*
// @include       *adserver.juicyads.com/*
// @include       *adm.soft365.com/*
// @include       *.com/ads/adsavess?*
// @include       *ads.creafi-online-media.com/*
// @include       *ads.lzjl.com/*
// @include       *ar.balagana.net/*
// @include       *ar.strawberrynet.com/*
// @include       *ar.vibramovil.com/*
// @include       *as.sexad.net/*
// @include       *cdn.adbooth.net/*
// @include       *d3.zedo.com/*
// @include       *popularprizes.allfreelyrics.com/*
// @include       *publicidad.mcanime.net/*
// @include       *res.soicos.net/*
// @include       media-fire.org/*
// @include       *notification.travian.com.ar/*
// @include       *recargar-celu.com/*
// @include       *zack0zackwww.youtube.com/watch?v=*&list=*
// @include       *zack0zackwww.youtube.com/*
// @include       *golotter.com/*
// @include       *lottery-win.org/*
// @include       *log.trendingnow.video/*
// @include       *discovernative.com/*
// @include       *get-express-vpn.com/*
// @include       *adrise.site/*
// @include       *thagodz.net/*
// @include       *sporetstream.com/*
// @include       *wtoday.net/*
// @include       *sba72x.1fichier.com/*
// @include       *demotrader.org/*
// @include       *signup.legendmajer.com/*
// @include       *adsrv.me/*
// @include       *signup.legenmajer.com/*
// @include       *172.255.6.133/*
// @include       *areantaid.site/*
// @include       *ofgogoatan.com/*
// @include       *badsways.com/*
// @include       *ofphanpytor.com/*
// @include       *es.888pokerworld.com/*
// @include       *best2019-games-web4.com/*
// @include       *zop381q5o0q1.com/*
// @include       *codere.mx/*
// @include       *extrementtgfa.site/*
// @include       *sg2rgnza7k9t.com/*
// @include       *regu-builder.club/*
// @include       *ps.popcash.net/*
// @include       *showyourevent.com/*
// @include       *https://iqoption.com/*
// @include       *vpwlynobnnqg.com/*
// @include       *t.co/*
// @include       *predictivdisplay.com/*
// @include       *nerve.eshkil.io/*
// @include       *bxaddbia.com/*
// @include       *geniusdexchange.com/*
// @include       *pushisback.com/*
// @include       *extyoasigus.com/*
// @include       *notification-centar.com/*
// @include       *paginasxalapa.com/*
// @include       *on4line.fun/*
// @include       *syndication.exdynsrv.com/*
// @include       *tychikigli.pro/*
// @include       *pin.rightvaluemedia.com/*
// @include       *1xbet.com.mx/*
// @include       *qfigzwpgzzkf.com/*
// @include       *serve.popads.net/*"
// @include       *popads.net/*vpwlynobnnqg.com/*
// @include       *888pokerworld.com/*
// @include       *asewlfjqwlflkew.com/*
// @include       *cradver.livejasmin.com/*
// @include       *xfreehdvideos.com/*
// @include       *hqxmovies.com/*
// @include       *xrisetube.com/*
// @include       *xupdatemovies.com/*
// @include       *bebreloomr.com/*
// @include       *v3m.gtarcade.com/*
// @include       *doubleadserve.com/*
// @include       *livehotty.com/*
// @include       *x9b05t5jsqje.com/*
// @include       *antivirus.hdviewer.net/*
// @include       *nummorum.money/*
// @include       *eamrx.getgirltofuck.net/*
// @include       *tr9ck.bruceleadx2.com/*
// @include       *1d5dddb91ec.traffic-c.com/*
// @include       *network.nutaku.net/*
// @include       *hotntubes.com/*
// @include       *sf.my.games/*
// @include       *apuestamx.com/*
// @include       *alucation.alugha.com/*
// @include       *routeumber.com/*
// @include       *alugha.com/*
// @include       *altasgine12.live/*
// @include       *altasgine12.*
// @include       *grushashuka.pro/*
// @include       *thefastpush.com/*
// @include       *fbcdn2.com/*
// @include       *iqoption.com/*
// @include       *tets.com/*
// @include       *server.cpmstar.com/*
// @include       *thebestgame2020.com/*
// @include       *nq93jx1vpq9r.com/*
// @include       *finnews-coin.com/*
// @include       *deliver.vkcdnservice.com/*
// @include       *signup.medusafun.com/*
// @include       *unelekidan.com/*
// @include       *runative-syndicate.com/*
// @include       *adskeeper.co.uk/*
// @include       *fagpodmum.site/*
// @include       *todays-winner.online/*
// @include       *silver-spirits.com/*
// @include       *lpg02.com/*
// @include       *widgets.adskeeper.com/*
// @include       *flixsport.co/*
// @include       *signup.medusanfun.com/*
// @include       *sdownload.net/*
// @include       *serconmp.com/*
// @include       *inpagepush.com/*
// @include       *cryptofuturo.world.com/*
// @include       *mgid.com/*
// @include       *thefxtips.club/*
// @include       *adskeeper.com.uk/*
// @include       *adskeeper*/*
// @include       *disqus.com/*
// @include       *publishers.disqus.com/*
// @include       *dadsats.com/*
// @include       *hadsabz.com/*
// @include       *osskanger.com/*
// @include       *statutorjiohui.site/*
// @include       *t.bawafx.com/*
// @include       *172.255.6.117/*
// @include       *idelv.net/*
// @include       *clickthatpush.com/*
// @include       *toomics.com/*
// @include       *securesafemembers.com/*
// @include       *creative.hpyrdr.com/*
// @include       *fastandslut.com/*
// @include       *mellowads.com/*
// @include       *statutorjuihui.site/*
// @include       *wargaming.net/*
// @include       *tgp1.rk.com/*
// @include       *codedexchange.com/*
// @include       *centent.streamplay.biz/*
// @include       *velocecdn.com/*
// @include       *ro7s8wo57qnb.com/*
// @include       *static.olymptrade.com/*
// @include       *nta1vb6cdlrl.com/*
// @include       *r6ztccbkdrbi.com/*
// @include       *signup.zumastar.com/*
// @include       *belombrea.com/*
// @include       *kreditiweb.mx/*
// @include       *devellingofrf.site/*
// @include       *ideliv.net/*
// @include       *.infopicked.com/*
// @include       *arbz.info/*
// @include       *clickks.net/*
// @include       *devellingofrf.*
// @include       *.realtime-bid.com/*
// @include       *clksite.com/*
// @include       *curmaphow.club/*
// @include       *moneybro.org/*
// @include       *s.optnx.com/*
// @include       *.optnx.com/*
// @include       *tosuicunea.com/*
// @include       *latestsocial.com/*
// @include       *signup.*.net/*
// @include       *wi3brxwr2b3v.com/*
// @include       *gadspmz.com/*
// @include       *lowtyroguer.com/*
// @include       *topflownews.com/*
// @include       *feurl.com/*
// @include       *itpatratr.com/*
// @include       *domainxchange.*/*
// @include       *financial-success-today.com/*
// @include       *cadsans.com/*
// @include       *motivation1success*/*
// @include       *fastfilles48speeder.tk/*
// @include       *doifuhdi6.club/*
// @include       *litdiarama.cf/*
// @include       *earandmarketing.com/*
// @include       *myartwork.space/*
// @include       *padsabz.com/*
// @include       *enraktina.ml/*
// @include       *pfepfe.info/*
// @include       *fgddl9szdof7.com/*
// @include       *xioodnxc1p1a.com/*
// @include       *expressvpn.com/*
// @include       *.findurlovemate.net/*
// @include       *bet365.mx/*
// @include       *binomo.com/*
// @include       *eikegolehem.com/*
// @include       *khg97644rvbg.com/*
// @include       *topmejorescasino.com/*
// @include       *elgraficosexo.com/*
// @include       *.klkus.xyz/*
// @include       *register.silverscreen.cc/*
// @include       *p102226.infopicked.com/*
// @include       *amigaslindas.com/*
// @include       *.monbin.site/*
// @include       *faracoon.com/*
// @include       *nuj20.proasdf.com/*
// @include       *elevantpds.club/*
// @include       *stockdelivery.co/*
// @include       *montances.club/*
// @include       *b3stcond1tions.com/*
// @include       *dudamapou.ml/*
// @include       *infopicked.com/*
// @include       *vevatom.com/*
// @include       *mobilevy.com/*
// @include       *protectdedication.com/*
// @include       *catastrophetray.com/*
// @include       *zmusic-online.com/*
// @include       *hkv06j2p7pof.com/*
// @include       *firescorrelationprodigy.com/*
// @include       *itnuzleafan.com/*
// @include       *searchsecurer.com/*
// @include       *wayfarerspoutpraise.com/*
// @include       *tapixesa.pro/*
// @include       *deedgeminctive.info/*
// @include       *trillonario.com.mx/*
// @include       *juxupsasu.pro/*
// @include       *nicsorts-accarade.com/*
// @include       *iqbroker.com/*
// @include       *astancerta.fun/*
// @include       *video-adblock.com/*
// @include       *ribunews.com/*
// @include       *streaming4free.com/*
// @include       *mysearchflow.com/*
// @include       *onstunkyr.com/*
// @include       *runheavily-therefinedfile.best/*
// @include       *cryptotabbrowser.com/*
// @include       *u-9204.onetouch6.com/*
// @include       *gooblesdd.com/*
// @include       *landing.jerkmate.com/
// @include       *ngp1.infopicked.com/*
// @include       *apuestasfree.com/*
// @include       *adverdirect.com/*
// @include       *hipfowlzeal.icu/*
// @include       *read-the-news.online/*
// @include       *fiefionfortes.casa/*
// @include       *install.onlinepdfconvertersearch.com/*
// @include       *bubblyalibiappear.com/*
// @include       *get-express-vpn.online/*
// @include       *jomtingi.net/*
// @include       *main.realsrv.com/*
// @include       *nutaku.net/*
// @include       *mariyadarg.fun/*
// @include       *ofhappinyer.com/*
// @include       *ethistory.xyz/*
// @include       *mqh-news5.club/*
// @include       *northtariffgallon.com/*
// @include       *ezhefg9gbhgh10.com/*
// @include       *onmarshtompor.com/*
// @include       *user-shield.com/*
// @include       *adblockstream.com/*
// @include       *passivemarcoanyhow.com/*
// @include       *getmyfiledownload.com/*
// @include       *p232207.infopicked.com/*
// @include       *latinogreet.com/*
// @include       *paid.outbrain.com/*
// @include       *uessentent.fun/*
// @include       *myfood.ltd/*
// @include       *p232207.mycdn.co/*
// @include       *louchees.net/*
// @include       *thefreshposts.com/*
// @include       *.123homepage.com/*
// @include       *.123loterie.com/consumer/consumer_subscribe.php?ori=*
// @include       *3rbmall.net/services/premium-accounts/megaupload/
// @include       *62.128.151.54/index.html?cod=*&redir=*
// @include       *69.31.136.5/defaults/sendspace-pop.html
// @include       *78.140.145.93/pop_up.html
// @include       *88.191.67.215/divers/redirector/redirector.php?c=*
// @include       *ace.jamba.fr/chaton_tendre/?pid=*
// @include       *actuweb.net*
// @include       *ad.jamba.fr/landingpages/*
// @include       *ad.smowtion.com/*
// @include       *ad.yieldads.com/st?ad_type=*
// @include       *.adcash.com/script/pop_packcpm.php?k=*
// @include       *adds.mobimezzo.com/*/*/?affid=*
// @include       *adf.ly/1IHI2
// @include       *adf.ly/4N75C
// @include       *adfoc.us/serve/?id=260139593
// @include       *adfoc.us/serve/?id=260139596
// @include       *ads.clicksor.com/showAd.php?nid=*
// @include       *.adscdn.com/ads/lp/bn/fr6/1.htm
// @include       *adstream.every.com/lpe/*
// @include       *advstat.letitbit.net/pop_up.html*
// @include       *advertising.gamelabs.de/storage/popup.php
// @include       *.aeriagames.com/*?utm_source=*
// @include       *.aldaniti.net/wingames/mercedes_fr/index.php?&
// @include       *amoureux.com/start.html?fromann=*_start&affi_partner=*
// @include       *.anavip.net/vb/*
// @include       *.angege.com/links.php?data=*
// @include       *arginfo.com/*
// @include       *.avendrealouer.fr/?utm_source=*&utm_medium=*&utm_campaign=*
// @include       *.avenue-des-credits.com/sumu/*
// @include       *.awsclic.com/*
// @include       *.azdsl.eu/*
// @include       *.be2.fr/?partnerid=*
// @include       *.beanfun.com/beanApp/xSignUp/JoinStep120111110.aspx?r=*
// @include       *.becoquin.com/aff.php?*
// @include       *.beezik.com/api/checkPub.htm?pid=*
// @include       *.beezik.com/memberAccountRegisterAffi.htm
// @include       *.betclic.fr/register_a.aspx?&p=*
// @include       *.betclic.fr/register_b.aspx?&p=*
// @include       *.bidrivals.com/fr/
// @include       *.bidrivals.com/fr/signup
// @include       *.bidrivals.directtrack.com/sw/*
// @include       *.*.bigpoint.com/big/*?aid=*
// @include       *.blinkogold.fr/fr/hippo2_plus.html?i=*
// @include       *.blinkogold.fr/fr/reveilouf1_son_plus.html?i=*
// @include       *.blog-de-manu.com/index2.php?source=mc_upload_popunder
// @include       *blog.manu83.com/index2.php?source=*
// @include       *blog-de-manu.com/index2.php?source=*
// @include       *.booster-trafic.net/adsredirect.htm?url=*
// @include       *.buyatimeshare.com/pop*
// @include       *.bwin.fr/sportsbook.aspx?pid=*
// @include       *.c-date.fr/
// @include       *.calivary.com/FR/ADS/*
// @include       *calivary.com/FR/ADS/*
// @include       *.campagne-promotion.com/pop*
// @include       *.cashtrafic.com/script/java.php?id=*
// @include       *.chatcontact.fr/*/?ptn=*
// @include       *click1.mainadv.com/ad.asp?id=*
// @include       *.combienjaidepoints.com/?utm_source=*
// @include       *.comment-je-gagne-7500euros-par-mois.com/?source=*
// @include       *.consultationdevoyance.com/*
// @include       *content.assurland.com/emailings/*
// @include       *content.promoisland.net/pop_up.html
// @include       *.consultationvoyance.com/*
// @include       *.couponwinner.com-net.info/lp1/?sid=*
// @include       *creatives.livejasmin.com/*
// @include       *creatives.livejasmin.com/iframes/*/*/*/*.swf
// @include       *.darkorbit.bigpoint.com/?aid=*
// @include       *dailydealspanel.com/fr/2/index2.php?s1=*
// @include       *dating-surf.com*
// @include       *default.pprgroup.net/redoute/dailyfr/
// @include       *.depositfiles.com/adroot/punder.html?url=*
// @include       *depositfiles.com/count_and_go.php?id=*&url=*
// @include       *.desert-operations.fr/register.html?rid=*
// @include       *.dragononline.ru/promo/*
// @include       *.drakensang-online.fr/big/*
// @include       *.edenflirt.com/?t=*
// @include       *.edenflirt.com/index.php?mrkgid=*
// @include       *.edenflirt.com/index.php?t=*
// @include       *.edreams.fr/vol/?utm_source=desmarket-FR&*
// @include       *.everestpoker.fr/promotions/offer/bonus/?utm_source=*
// @include       *.farmerama.fr/*?aid=*
// @include       *.femme-cougar.tv/?utm_source=*$popup
// @include       *flash.9df9.com/
// @include       *.forexagone.com/intro.html?source=popupUpload*
// @include       *fr.minisite.12coupsdemidi.fr/12000euros/
// @include       *.freelotto.com/register.asp?skin=*
// @include       *gagner-argent-facile.biz*
// @include       *gagnons-argent.com/*
// @include       *gallendor.*/*
// @include       *.gigasize.com/affiliate
// @include       *.girlfriendhookup.net/lp/?sid=*
// @include       *.gladiatus.fr/game/?kid=*
// @include       *.globalconsumerwinner.com/vcb/*
// @include       *goo.gl/s4dje
// @include       *.groupon.fr/sites/*
// @include       *.groupon.fr/?CID=*
// @include       *httptrack.com/ad.asp?id=*
// @include       *.ikariam.com/?kid=*
// @include       *jeux.gagnant-du-jour.com/*
// @include       *.kdo-mobile.fr/multi_actu?referer=*
// @include       *.kko-sonneries.fr/demo_bebe%20sumo_415559.html?referer=*
// @include       *.kpol.free-h.fr/FS/c/?id=*
// @include       *img1.imagehyper.com/img.php?id=362140&c=12e3c7b926daecdbb302053f9c95b580
// @include       *.imvu.com/catalog/web_landing.php?*
// @include       *.jeu-a-telecharger.com/*?ptn=*
// @include       *justrich.net
// @include       *.laredoute.fr/?adsite-under
// @include       *lb.flingvibe.com/mup/*
// @include       *le-grand-quiz-meteo.tf1.fr/?v=*
// @include       *.liens-vip.com/jeux/jeux.php?id=*
// @include       *.les-malins-du-jour.com/trk/sumu/*
// @include       *.les-options-binaires.com/landing*
// @include       *.loptionbinaire.com/*
// @include       *lp1.ikkotrader.com/lp/*
// @include       *lpop.usafis.org/sys/yes_you_can_banner.php?af=*
// @include       *manu83.com/index2.php?source=*
// @include       *.mate-et-tchat.com/?tc*
// @include       *.meeticaffinity.fr/signup/landing_a.php?mtcmk=*
// @include       *.megaclick.com/ad.code?de=*&tm=*&du=*
// @include       *.megacasino.com/FR/?aff=*
// @include       *.megavod.fr/?ptn=*
// @include       *.mes-revenus-domicile.com/index2.php?source=*
// @include       *mgid.com/mg*.html
// @include       *.mktmobi.com/*/adv-*.html
// @include       *.miramagia.fr/?ad=*
// @include       *.mixmasteronline.fr/ad.php?*
// @include       *mlgame.fr/?state=register_simple&ref=*
// @include       *.mobifiesta.com/*/?ptn=*
// @include       *.mobijeux.com/*?ptn=*
// @include       *.multiupload.com/popunder/*
// @include       *notification.travian.fr/?box&ad=*
// @include       *.novaflat.com/browse-best/
// @include       *.on-se-mate.com/?tc*
// @include       *outils.yesmessenger.com/pdv40.php?id=*
// @include       *.originalstring.com/
// @include       *outils.yesmessenger.com/*&tracker=*
// @include       *ov1.ludostart.com/*
// @include       *partners.bidrivals.com/*
// @include       *.partypoker.com/td/*
// @include       *.partypoker.fr/td/*
// @include       *.pgmediaserve.com/*/
// @include       *.pimpmonmobile.com/ws/acp?sp=*
// @include       *.piratestorm.fr/*?aid=*
// @include       *.pixmania.com/fr/fr/*/index.html?nopopup=*
// @include       *.pixmania.com/fr/fr/*.html?nopopup=*
// @include       *player.antennesport.fr/pub.php
// @include       *.pokerstrategy.com/about/?referer=*dpf_*
// @include       *.pokerstrategy.com/bankroll/megaupload/*
// @include       *.popupcheck.com/popup_manual/page.asp
// @include       *.popuptest.com/popup2.html
// @include       *.popuptest.com/popup3.html
// @include       *.popuptest.com/popup4.html
// @include       *.popuptest.com/popup9.html
// @include       *.popuptest.com/popup10.html
// @include       *.prizee.com/inscription/?idt=*
// @include       *prizewinner.com-org.biz/win/*
// @include       *promotions.djummer.com/*
// @include       *promo.chatcontact.fr/?ptn=*
// @include       *promo.fantazium.ru/*
// @include       *promo.vador.com/*
// @include       *pubdirecte.com/?ref=*
// @include       *pubdirecte.com/script/*
// @include       *register.fr.perfectworld.eu/pwiad10
// @include       *.rencontre-beurette.tv/?utm_source=*
// @include       *.rencontre-cougar.tv/?utm_source=*
// @include       *.repeindremonappartement.com/*
// @include       *.retrogamer.com/dl/index.jhtml?partner=*
// @include       *rtpartnerip.every.com/*
// @include       *.ruedesjoueurs.com/V4/*/*.html
// @include       *.runesofmagic.com/fr/free-mmo/index.html
// @include       *.secretstorylejeu.fr/signup.php?idc=*
// @include       *.seesaam.com/ad1.php
// @include       *serw.clicksor.com/*
// @include       *serw.clicksor.com/newServing/links.php?zone=*
// @include       *.shoes.fr/soldes.php?track_id=*
// @include       *.skyrama.fr/*?aid=*
// @include       *.smartdate.com/?utm_source=*
// @include       *.sonnerie-mobile-kdo.com/*?referer=*
// @include       *.spartoo.com/soldes.php?track_id=*
// @include       *.tchat-rose.com/?tc*
// @include       *.telephoneo.fr/accessoires-pour-telephone-portable/*
// @include       *.the-adult-company.com/*
// @include       *.the-adult-company.com/fpage/dial-coquin/*
// @include       *.theconsumerwinner.com/vcb/star_intl/s_int_index_d.php?lp=*
// @include       *.themoteur.com//?utm_source=*
// @include       *tour.cinejam.com/movie_player_fr/index?ref=*
// @include       *tour.flixbuster.com/movie_player_fr/index?ref=*
// @include       *.tourisme-promo.fr/pop*
// @include       *.travian.fr/landingpage/*
// @include       *.tringaloo.com/ApplePackage/*
// @include       *.tringaloo.com/iPhone4Quiz/*
// @include       *.tringaloo.com/MegaUploadQuiz/*
// @include       *.tringaloo.com/WinYouriPhoneMegaQuiz/*
// @include       *.tringaloo.com/YourMacBookProQuiz/*
// @include       *.tt-ads.com/*
// @include       *.usershare.net/yabkiu003279
// @include       *valentinehookup.com/lp/*
// @include       *vgmc.com/*
// @include       *.vidcube.com/movie_player_fr/index?ref=*
// @include       *.vipmobile.fr/sims3.aspx?source=*
// @include       *.visio-rose.com/?tc[]=mc&tc[]=mup_popunder
// @include       *.war2glory.fr/?source=*
// @include       *.wargame1942.fr/register.html?rid=*
// @include       *.wawacity.ws/popup.html
// @include       *.weeklyprizewinner.com-net.info/winner/?sid=*
// @include       *.wheresjenny.com/*
// @include       *.woozgo.fr/*&ptn=*
// @include       *.zedo.com/*
// @include       *zpag.es/4CdG
// @include       *superflat-vodafone*/*
// @include       *admention*
// @include       *de.foto.*/*
// @include       *sponsorads*
// @include       *lan.bin-layer*
// @include       *bitdefender*
// @include       *layer-ads*
// @include       *zonealarm*
// @include       *spickmich*/dollar-verdient?id=*
// @include       *spickmich.*/wirklich-du?ref=%*Fdollar-verdient%*Fid%*
// @include       *yooliety*/wtClick.php?id=*
// @include       *.kleine-stadt.*/
// @include       *s2.gladiatus*/game/c.php?uid=*
// @include       *.myminicity.*/
// @include       *drogendealer*/cgi-bin/ddlanding.cgi?res=m&cpid=1&ref=*
// @include       *my-schamhaar*/showpage.php?uid=*
// @include       *zooperstar.*/photo-*.html
// @include       *hanf-spiel*/*
// @include       *koelschgame*/trink.php?id=*
// @include       *bongspiel*/*
// @include       *klick4views.*/register.php?referer=*
// @include       *dasdeutschlandspiel*/index.php?page=beg.php&id=*
// @include       *bierschank.dragulsreich*/bier/schenk.php?op=*
// @include       *neckermann*/*/*,de_DE,sc.html
// @include       *neckermann.*/*/demandware*
// @include       *neckermann.*/Kategorie*
// @include       *elektronik-star*/?__comes_from=affiliwelt&campaign=affiliwelt/Allgemein/logo-120x60
// @include       *bitefight*/bite/c.php?uid=*
// @include       *squiby.net/level/*
// @include       *w*.gondal*/signups/add?subid=ref*
// @include       *w*.gondal.*/robbers/me/*
// @include       *gimigames*/ascalepop.php
// @include       *om.mi.1und1.*
// @include       *volvocars.*/*/*/*
// @include       *change.pennergame*/change_please/*/
// @include       *berlin.pennergame.*/change_please_action/*/
// @include       *change.dossergame.co.uk/change_please/*/
// @include       *change.menelgame.pl/change_please/*/
// @include       *clodogame.fr/change_please/*/
// @include       *cambio.mendigogame.es/change_please/*/
// @include       *muenchen.pennergame.*/change_please/*/
// @include       *knightfight*/?ac=vid&vid=*
// @include       *hackthenet.*/_htn.php/pub/hack/*/*
// @include       *klammgeil.*/beg.php?&id=*&weiter=1&urles=&code=*
// @include       *klammgeil.*/page.php?ref=*
// @include       *freedomresist.*/?ac=vid&vid=*&ref=link&language=*
// @include       *monstersgame.*/?ac=vid&vid=*
// @include       *monstersgame.*/index.php?ac=showclan&showclanid=*
// @include       *wurzelimperium*/*/index.php?mode=*&user=*
// @include       *wurzelimperium.*/?ref=*
// @include       *kabeldeutschland*/index.html?source=zanox
// @include       *versatel-internet*/index.php?*=*&*_*=*
// @include       *doppelzelle.*/postAct/?zelle=*
// @include       *doppelzelle.*/besuchAct/?zelle=*
// @include       *doppelzelle.*/besuchDo*
// @include       *bananenkoenig.*/?ac=vid&vid=*
// @include       *metaldamage.*/game/c.php?uid=*
// @include       *techwarrior.*/?ac=vid&vid=*
// @include       *wewaii.*/hotel/?id=*
// @include       *zarenkriege.*/?recruit=*
// @include       *bergthron.*/*.html
// @include       *.molehillempire.*/garden/index.php?mode=view&user=*
// @include       *spenden-community.*/top.php?id=*&tabelle=*
// @include       *spenden-community.*/check.php?url=*
// @include       *spenden-community.*/check.php?leer=TRUE&url=*
// @include       *ad.zanox.*
// @include       *dragosien.*/user/*
// @include       *maxdome.*/?affiliate=*
// @include       *channel21.*/shop/*
// @include       *stayfriends.*/?AdrHId=*
// @include       *stayfriends.*/?*inladung=*
// @include       *tinyreg.stayfriends.de/*
// @include       *.funpic.*/wbblite/?*=*
// @include       *burningmails.*/paidklick.php?ref=*
// @include       *comdirect.*/pbl/cms/*
// @include       *gamesload.*/kalender/*_kalender*
// @include       *tom-tailor.*/?view=*
// @include       *media.fastclick.*
// @include       *deepolis.bigpoint.*/?aid=*
// @include       *webmasterebesucher.*
// @include       *jappy.*/?utm*
// @include       *nur2euro.*/index.php?mod=*&*=*
// @include       *quisma.*/tracking/*
// @include       *promo.awempire*
// @include       *tele2.*/Privatkunden/*
// @include       *loomondo.*/landingpage*
// @include       *dslshop.vodafone.*/eshop/consumer*
// @include       *musicstar.*/produkt*
// @include       *primeraparadies.*/bettel.php?usr=*
// @include       *my-capital.*
// @include       *performance-netzwerk.*
// @include       *adsfac.*
// @include       *adscale.*
// @include       *sexpartnerclub.*
// @include       *o2-freikarte.*/affiliate*
// @include       *1und1.*/xml*
// @include       *gladiatus.*/game*
// @include       *vodafone.*/Shop/picknmix*
// @include       *t-home.*/komplettpakete*
// @include       *cosmosdirekt.*
// @include       *serving-sys.*
// @include       *gilde1400.*/?kid=*
// @include       *videoload.*/c/*
// @include       *bitefight.*/?kid=*
// @include       *foxtv.de/24*
// @include       *surftausch.*/betteln.php?user=*
// @include       *feelgood-shop.*/index.php?affiliate*
// @include       *klick-game.*/archiv-*
// @include       *adfarm1.adition*
// @include       *paypal-deutschland.*/shops/*
// @include       *da-direkt.*/*-banner*
// @include       *sportscheck.*INTERSHOP*
// @include       *bigpoint.*/?aid=*
// @include       *alice-dsl.*kundencenter*
// @include       *spreadshirt.*T-Shirt-gestalten*
// @include       *whiskas.*/Content*
// @include       *t-home.*/call-und-surf*
// @include       *snoogmobile.*
// @include       *steal-money.*/spiel.php?id=*
// @include       *1822direkt.*/1822central*
// @include       *mechrage.*/?rid=*
// @include       *mmoga.*/?gclid=*
// @include       *gmx.*/*Flatrate*
// @include       *spenden.greenpeace.*/urwald_*
// @include       *aka-cdn-ns*
// @include       *nokia.*/produkte*
// @include       *allsecur.*/start*
// @include       *o2online.*/*/handys*
// @include       *epson-store.*
// @include       *blitz-verdienst24.*/paidklick.php?user=*
// @include       *sponsortown.*
// @include       *deinpunkt.*/home*
// @include       *klick-game.*/*-Jahr*
// @include       *klick-game.*/seite-*
// @include       *galaxylose.*/paidklick.php?user=*
// @include       *mobiles-internet.gmx.*
// @include       *portal.gmx.*
// @include       *takeyourownpath.*
// @include       *sky.*/web*
// @include       *das-forum.*/popunder.php
// @include       *romantik-mailer.*/paidklick.php?user=*
// @include       *teldafax.*/strom*
// @include       *smarte-geldkarte.*/startseite*
// @include       *mercedes-benz.*/content*
// @include       *allianz.*/produkte*
// @include       *brigitte.*/kultur-kalender
// @include       *meinauto.*/?ref=*
// @include       *spickmich.*/friendship?action=ask&sid=*
// @include       *stream.utarget.*
// @include       *rentthenewpolo.*/?local=*
// @include       *mp-success.*
// @include       *seafight.*/?aid=*
// @include       *swarovski.*/Web_*
// @include       *bidwiz.*/default.asp?ref=*
// @include       *e-wie-einfach.*/gewinnspiel*
// @include       *die-staemme.*/*-de*.html
// @include       *lose-dieb.*
// @include       *paid4-clicks.*/anmeldung.php?ref=*
// @include       *paid4ad.*
// @include       *eteleon.*/shop*
// @include       *bmw-cabrio-gewinnen.*
// @include       *traffic-base.*
// @include       *conegi.*
// @include       *tvister.*
// @include       *dealstreet.*
// @include       *vielebesucher.*
// @include       *wunschkiste.*
// @include       *spidercash.*/index.php?refid=*
// @include       *point-mail.*/anmeldung.php?ref=*
// @include       *blue-ice.*
// @include       *blackpantherweb.*
// @include       *kiras-mailer.*
// @include       *am-infoparadies.*
// @include       *am-proservice.*
// @include       *zandoon.*/signups*
// @include       *11813-auskunft.*/preisvergleich*
// @include       *highscoreshop.*
// @include       *lead-mailer.*/paidklick.php?user=*
// @include       *energiewelt.*
// @include       *nuttenspiel.*/*.php?referer=*
// @include       *zedmobil.*
// @include       *dpbolvw.*
// @include       *lidl-shop.*
// @include       *esprit.*
// @include       *ondarun2.*
// @include       *iphone.*.*/index*
// @include       *superclix.*
// @include       *adcell.*
// @include       *platoon-sniper.*/anmeldung.php?ref=*
// @include       *moorbacher.*.*/Paid/index*
// @include       *caseking.*/shop*
// @include       *premingo.*
// @include       *moorbacher.*.*/?page=*
// @include       *mail-power.*/?refid=*
// @include       *gewittermails.*/anmeldung.php?ref=*
// @include       *platoon-mailer.*/index.php?ref=*
// @include       *losecounter.*/*.php?id=*
// @include       *googleads*
// @include       *newtention.*
// @include       *myfreefarm.*/?ref=*
// @include       *tarifcheck24.*/landingpage*
// @include       *mailgold.de/?refid=*
// @include       *crimestyle.*/generalclickmore.php?x=*
// @include       *paidsolution.*
// @include       *soleara.*
// @include       *partycasher.*/index.php?mod=begging&user=*
// @include       *neujahrsmailer.*/paidklick.php?user=*
// @include       *dsn-ads.*/data/werbung*
// @include       *contest.bbgsite.*/gameprize/webapps/?controller=game&id=*
// @include       *t-online-shop.*/tonline/start*
// @include       *ab-in-den-urlaub.*/?tc_unister=*
// @include       *cashcrawler.*/join.php?ref=*
// @include       *klick-game.*.*.*/*
// @include       *supportfox.*/besuta4/diebspiel.php?bn=raikli&ref=*
// @include       *paidmailbus.*/schwarzfahren.php?ref=*
// @include       *popup*.nextlevelads.*
// @include       *crazyhammer.*/index.php?newsref=*
// @include       *kohlenpfote.*/paidklick.php?user=*
// @include       *generate-your-life.*.*/dieb/index.php?user=*
// @include       *klamm-mafia.*/index.php?content=site/betteln&bettelnick=*
// @include       *calimeromailer.*/paidklick.php?user=*
// @include       *adstage.*/paidklick.php?user=*
// @include       *klamm-mafia.*/index.php?content=site/betteln&bettelnick=*&werber=*
// @include       *wirb-oder-stirb.*/index.php?mod=begging&userid=*&refid=*
// @include       *generate-your-life.*/dieb/index.php?user=*&id=*
// @include       *smartbux.*/index.php?ref=*
// @include       *mary-johanna.*/*.html
// @include       *league4u.*/ref/*/*.html
// @include       *automatischer-besuchertausch.*/betteln.php?user=*
// @include       *server*.lunafabula.*/index.php?page=register&pid=*
// @include       *clickmonster.*/index.php?ref=*
// @include       *mycare.*/home/?*_source=superclix*
// @include       *forced-lose.*/*/popc*
// @include       *earnstar.*/?ref=*
// @include       *clockworkinvestment.*/?upline=*
// @include       *maxdome.de/exchange/affiliate/videos/maxdome_popunder*
// @include       *ad.yieldmanager.*
// @include       *cabal.*/?kid=*
// @include       *kioskgame.de/visit.php?id=*
// @include       *insektenschutz-systeme.*/epages/*
// @include       *mailtausch.*/paidklick.php?user=*
// @include       *klick-game.*/joke-*.html
// @include       *punktemailer.*/bettel.php?user=*
// @include       *neu.*/signup/landing.php?*
// @include       *airtransat.*/*-fluge/index.*
// @include       *maxdome.*/exchange/affiliate/videos/maxdome_popunder*
// @include       *kapiland.*/?ref=*
// @include       *mypaqe.*/siteid/*
// @include       *generate-your-life.*/dieb/spiel.php?id=*
// @include       *schulterglatze.*/spenden/*
// @include       *opencms.adscale.*/ads/stayfriends/*/popunder.html
// @include       *s*.kapibados.*/schaugarten/index.php?mode=view&user=*
// @include       *spielwelt*.talesofmagic.*/?c=*&*=*
// @include       *.albert-learning.com/*
// @include       *.123homepage.com/ads/*
// @include       *.65vk1fba34.com/*
// @include       *65vk1fba34.com/*
// @include       *actuweb.net/*
// @include       *.awsclic.com/?9311
// @include       *.awsclic.com/?11896
// @include       *.awsclic.com/l/1166618
// @include       *.awsclic.com/l/1192794
// @include       *.awsclic.com/l/617550
// @include       *.awsclic.com/l/806743
// @include       *.azdsl.eu/fr/aDIfr.asp
// @include       *flash.9df9.com/*
// @include       *.popuptest.com/popuptest1.html
// @include       *.popuptest.com/popup1.html
// @include       *valentinehookup.com/lp/*
// @include       *.wawacity.ws/*
// @include       *cjl58f3agc.com/*
// @include       *tracking.perfecttoolmedia.com/*
// @include       *myornamenti.com/*
// @include       *fembed.com/*
// @include       *ropleftinwaref.info/*
// @include       *u2rn.ropleftinwaref.info/*
// @include       *y45r.ropleftinwaref.info/*
// @include       *arebronthenrollet.info/*
// @include       *es.usenet.nl/*
// @include       *enoughts.info/*
// @include       *rdho.ropleftinwaref.info/*
// @include       *.ropleftinwaref.info/*
// @include       *.ropleftinwaref.*/*
// @include       *empiece-a-comerciar.com/*
// @include       *browsergames2019.com/*
// @include       *fembed*
// @include       *heroesofrpg.com/*
// @include       *theersoa.net/*
// @include       *.beetle-clicks.biz/*
// @include       *arebronthenrollet.*/*
// @include       *greetham.net/*
// @include       *zuzodoad.com/*
// @include       *bet365.com/*
// @include       *deloplen.com/*
// @include       *xilbalar.com/*
// @include       *fiverdtzbx.*/*
// @include       *fiverdtzbx.xyz/*
// @include       *nanoadexchange.com/*
// @include       *.nanoadexchange.com/*
// @include       *6uwehz1xp4.com/*
// @include       *allornamenti.com/*
// @include       *16yp1ji92a.com/*
// @include       *1zv9jakhux.com/*
// @include       *vjltrbzrtqmkib.com/*
// @include       *yr9n47004g.com/*
// @include       *0byv9mgbn0.com/*
// @include       *43yagowe3y.com/*
// @include       *4l7wg5kf3z.com/*
// @include       *l6b587txj1.com/*
// @include       *mnoa6ez1eq.com/*
// @include       *gmidkz5tgm.com/*
// @include       *udrivemyr54.com/*
// @include       *onclicksuper.com/*
// @include       *nextyourcontent.com/*
// @include       *.nextyourcontent.com/*
// @include       *lp.easyziptab.com/*
// @include       *.easyziptab.com/*
// @include       *allmygreatestlife.com/*
// @include       *allmyverygreatlife.com/*
// @include       *aud3g.com/*
// @include       *mzol7lbm.com/*
// @include       *s20dh7e9dh.com/*
// @include       *u21drwj6mp.com/*
// @include       *9h7n8.com/*
// @include       *ie3wisa4.com/*
// @include       *pbterra.com/*
// @include       *pl144125.puhtml.com/*
// @include       *98bf9h8jbg.com/*
// @include       *bnsjb1ab1e.com/*
// @include       *wvhba6470p.com/*
// @include       *0sntp7dnrr.com/*
// @include       *1.biqle.ru/*
// @include       *4v9wp.com/*
// @include       *59cn7.com/*
// @include       *clicksgear.com/*
// @include       *3z6hirxo24.com/*
// @include       *y6a7tqyr.com/*
// @include       *b42rracj.com/*
// @include       *5odjin7ipi.com/*
// @include       *f09vhflf10.com/*
// @include       *terraclicks.com/*
// @include       *tj9pcnb2ws.com/*
// @include       *e7is2u38.top/*
// @include       *ig0nr8hhhb.com/*
// @include       *rgvqcsxqge.com/*
// @include       *cpmpop.com/*
// @include       *49oa3o49b6.com/*
// @include       *dpypzvjarj.com/*
// @include       *0naa190101.mobi/*
// @include       *allmygreatlife.com/*
// @include       *find-my-great-life.com/*
// @include       *2fwww.ecpms.net/*
// @include       *4o64flb.com/*
// @include       *vidsdelivery.com/*
// @include       *45eijvhgj2.com/*
// @include       *7s08gpbp39.com/*
// @include       *pl2127.puhtml.com/*
// @include       *putrr18.com/*
// @include       *4f2sm1y1ss.com/*
// @include       *9amq5z4y1y.com/*
// @include       *b3z29k1uxb.com/*
// @include       *osny2p7a0k.com/*
// @include       *p9oqu.com/*
// @include       *pussl37.com/*
// @include       *9purdfe9xg.com/*
// @include       *dnr51y6xj4.com/*
// @include       *c0cd2idcl5.com/*
// @include       *kip5j.com/*
// @include       *qth7n6akcr.com/*
// @include       *viriepak.com/*
// @include       *putrr12.com/*
// @include       *6kup12tgxx.com/*
// @include       *ornament-i.com/*
// @include       *ouradse.com/*
// @include       *1.fembed.com/*
// @include       *.fembed.com/*
// @include       *6zw2rcfd.com/*
// @include       *adqy6rzwcs.com/*
// @include       *cpm20.com/*
// @include       *oicssiq.com/*
// @include       *truefilen32.com/*
// @include       *djrvqpg.com/*
// @include       *pl114239.puhtml.com/*
// @include       *jqzzqsm.com/*
// @include       *hnnp4ixxkl.com/*
// @include       *jf71qh5v14.com/*
// @include       *sdreif.com/*
// @include       *pl132863.puhtml.com/*
// @include       *ipbsgpm4.top/*
// @include       *newoctads.com/*
// @include       *newsunads.com/*
// @include       *newyearads.com/*
// @include       *x3w7lvezss.com/*
// @include       *14269848.ilo134ulih.com/*
// @include       *eawp2ra7.top/*
// @include       *mse2v5oglm.com/*
// @include       *pl105492.puhtml.com/*
// @include       *pussl33.com/*
// @include       *pussl36.com/*
// @include       *6d79qh7j.com/*
// @include       *zvhuevqkmv.com/*
// @include       *ajjhtetv87.com/*
// @include       *btvhdscr.com/*
// @include       *nfkd2ug8d9.com/*
// @include       *s4yxaqyq95.com/*
// @include       *0gctp5ht.top/*
// @include       *hwekl8dz1d.com/*
// @include       *mobile.dh956.com/*
// @include       *ssl4anyone2.com/*
// @include       *wzdzht7am5.com/*
// @include       *78tdd75.com/*
// @include       *xev2o.com/*
// @include       *pl11300103.puhtml.com/*
// @include       *clickmngr.com/*
// @include       *putrr16.com/*
// @include       *1paj4kmp.top/*
// @include       *count.puhtml.com/*
// @include       *ths9j89.com/*
// @include       *kt5850pjz0.com/*
// @include       *newfebads.com/*
// @include       *Sd5DoOzRy8.com/*
// @include       *vneffwecka.com/*
// @include       *2iiyrxk0.com/*
// @include       *b84pharkhv.com/*
// @include       *hicpm10.com/*
// @include       *hitcpm.com/*
// @include       *putrr13.com/*
// @include       *vidcpm.com/*
// @include       *gfbnr.com/*
// @include       *zxwiejfbyr.com/*
// @include       *65xps.com/*
// @include       *d0p21g2fep.com/*
// @include       *d0v5g1vb.top/*
// @include       *mygoodlives.com/*
// @include       *pl105956.puhtml.com/*
// @include       *newsatads.com/*
// @include       *newwedads.com/*
// @include       *ikwauek.com/*
// @include       *newaprads.com/*
// @include       *newdecads.com/*
// @include       *newfriads.com/*
// @include       *newjanads.com/*
// @include       *newjunads.com/*
// @include       *newmarads.com/*
// @include       *newmayads.com/*
// @include       *newmonads.com/*
// @include       *newnovads.com/*
// @include       *newsepads.com/*
// @include       *lp.browsers.support/*
// @include       *newaugads.com/*
// @include       *newjulads.com/*
// @include       *newtueads.com/*
// @include       *3r1kwxcd.top/*
// @include       *irgulzk8bi.com/*
// @include       *newthuads.com/*
// @include       *pl118422.puhtml.com/*
// @include       *clickterra.net/*
// @include       *hoo1luha.com/*
// @include       *3b9675ljcw.com/*
// @include       *gld35wndkn.com/*
// @include       *0f81i8zmcp.com/*
// @include       *1ea1sley.com/*
// @include       *dessertcount.com/*
// @include       *domaintmt.tumejortorrent.com/*
// @include       *forum.hitcpm.com/*
// @include       *ccumhss.com/*
// @include       *bqiovml.com/*
// @include       *pl161407.puhtml.com/*
// @include       *uod2quk646.com/*
// @include       *goo4anywhere.com/*
// @include       *keqi7dh3df.com/*
// @include       *lvgvax82bp.com/*
// @include       *x7xirtzmot.com/*
// @include       *xu5ctufltn.com/*
// @include       *6l1twlw9fy.com/*
// @include       *hg8dc7bm.com/*
// @include       *e9geolgzk6.com/*
// @include       *fd7qz88ckd.com/*
// @include       *tfa5e.top/*
// @include       *8ue9q7i.com/*
// @include       *edua29146y.com/*
// @include       *si1ef.com/*
// @include       *ssl2anyone3.com/*
// @include       *a9nf3hg5c2.com/*
// @include       *q64a9ris0j.com/*
// @include       *t2f9pn3m7w.com/*
// @include       *puhtml.com/*
// @include       *aaucwbe.com/*
// @include       *ext.trafficbroker.xyz/*
// @include       *j9j6l.top/
// @include       *xqkzsifxgv.com/*
// @include       *2lwlh385os.com/*/*
// @include       *mbcjufwxg9.com/*
// @include       *pl6456857.puhtml.com/*
// @include       *96n5r5va.top/*
// @include       *kzws02uffs.com/*
// @include       *pl151979.puhtml.com/*
// @include       *pl156919.puhtml.com/*
// @include       *rrtcfwmvhs.com/*
// @include       *11hrcnll.com/*
// @include       *dt2xr6g2i5.com/*
// @include       *huangguandaxiao.si1ef.com/*
// @include       *ktf5kbl2m4.com/*
// @include       *ldt1duixoe.com/*
// @include       *myusersoffer.com/*
// @include       *putrr5.com/*
// @include       *modulepush.com/*
// @include       *pl105957.puhtml.com/*
// @include       *vy4e3jw46l.com/*
// @include       *79zgycmr.com/*
// @include       *hf18yg8q.com/*
// @include       *05y2dxmr.top/*
// @include       *pl172072.puhtml.com/*
// @include       *v5yfi7sy.com/*
// @include       *pussl38.com/*
// @include       *putrr15.com/*
// @include       *2gok8g15p2.com/*
// @include       *bxnvdau.com/*
// @include       *pl161166.puhtml.com/*
// @include       *19bk5lo5q2.com/*
// @include       *thxczhfzad.com/*
// @include       *xgrwjbui.top/*
// @include       *www.mtvp05j.com/*
// @include       *terraviewnow.com/*
// @include       *tkekbn5sfk.com/*
// @include       *h5tjj3loy2.com/*
// @include       *ylskyueqya.com/*
// @include       *6jvt2.top/*
// @include       *ilo134ulih.com/*
// @include       *nepalhtml.com/*
// @include       *terraviewfly.com/*
// @include       *s5prou7ulr.com/*
// @include       *v3rjvtt.com/*
// @include       *0azx1.com/*
// @include       *8iqpy8cgkk.com/*
// @include       *hicpm5.com/*
// @include       *qjjto.com/*
// @include       *1wkvvts8is.com/*
// @include       *cvqgnkeqme.com/*
// @include       *vinfdv6b4j.com/*
// @include       *g27zkdvsxl.com/*
// @include       *eecd179r3b.com/*
// @include       *indlzxgptf.com/*
// @include       *0ql3xxre2h.com/*
// @include       *13vm73vbmp.com/*
// @include       *3221dkf7m2.com/*
// @include       *42632zfylf.com/*
// @include       *5nt1gx7o57.com/*
// @include       *6kauqbszb9.com/*
// @include       *6ped2nd3yp.com/*
// @include       *7fkm2r4pzi.com/*
// @include       *7hor9gul4s.com/*
// @include       *as07d698u9.com/*
// @include       *bl0uxepb4o.com/*
// @include       *cfts1tifqr.com/*
// @include       *exi8ef83z9.com/*
// @include       *fiv2yl8dct.com/*
// @include       *gqqdlckj8y.com/*
// @include       *hghm4u7b61.com/*
// @include       *kwnq4hg2n9.com/*
// @include       *mgti1kofb8.com/*
// @include       *muqson0kgr.com/*
// @include       *nhpfvdlbjg.com/*
// @include       *qkpcihpo16.com/*
// @include       *t7479e4d.com/*
// @include       *pl117310.puhtml.com/*
// @include       *terraads.net/*
// @include       *pl1689.puhtml.com/*
// @include       *qy1bx9an4j.com/*
// @include       *y1jxiqds7v.com/*
// @include       *4ojwnsgub2.com/*
// @include       *6u4dxh2f14.com/*
// @include       *ns4.terraads.net/*
// @include       *pl11728357.puhtml.com/*
// @include       *pl156922.puhtml.com/*
// @include       *ww2.imgadult.com/*
// @include       *.imgadult.com/*
// @include       *imgadult.com/*
// @include       *ww2.imgdrive.net/*
// @include       *.imgdrive.net/*
// @include       *280asnlnr7.com/*
// @include       *2ypmo2nhgf.com/*
// @include       *31y6b8omk2.com/*
// @include       *o7coh5tlwb.com/*
// @include       *wweew.jolic2.com/*
// @include       *0a0qetx8et.com/*
// @include       *2taa9ib4ib.com/*
// @include       *domainpctn.pctnew.com/*
// @include       *mhbdezpwdq.com/*
// @include       *2ptxxjjzpy.com/*
// @include       *domaind2020.descargas2020.com/*
// @include       *domaintrp.torrentrapid.com/*
// @include       *pl1100.puhtml.com/*
// @include       *421npyd4nd.com/*
// @include       *6f2tjr26.top/*
// @include       *rmawm7mw.top/*
// @include       *lhqojeofvo.com/*
// @include       *px1alsry.com/*
// @include       *zjo0tjqpm1.com/*
// @include       *1wvw2jgkca.com/*
// @include       *1x96klcdpn.com/*
// @include       *3gkd6funzz.com/*
// @include       *4aqi9vrzr2.com/*
// @include       *51nlno7cgy.com/*
// @include       *5z8museor8.com/*
// @include       *6dbac32rsl.com/*
// @include       *74im4p7xq6.com/*
// @include       *8br8gm2r15.com/*
// @include       *93rrp02wqh.com/*
// @include       *afcwyxnwl0.com/*
// @include       *ah8asl94hs.com/*
// @include       *caai83kh6p.com/*
// @include       *fqvkntefmd.com/*
// @include       *guo1x952bi.com/*
// @include       *kdc7f2ifcc.com/*
// @include       *koo6myletj.com/*
// @include       *lh7e9xjy5x.com/*
// @include       *lxpx813cta.com/*
// @include       *meuzxiejun.com/*
// @include       *np1t0bcj0n.com/*
// @include       *qaykb.com/*
// @include       *ql6401rkow.com/*
// @include       *01jud3v55z.com/*
// @include       *3grsomcook.com/*
// @include       *be4anywhere.com/*
// @include       *explore2be.com/*
// @include       *g1xgeb82nj.com/*
// @include       *pgh76i5ya5.com/*
// @include       *2go7v1nes8.com/*
// @include       *9jwas.top/*
// @include       *cfduid.push-notifications.top/*
// @include       *mail.pbterra.com/*
// @include       *ns3.terraads.net/*
// @include       *0n55f9zgy7.com/*
// @include       *157ita684j.com/*
// @include       *2kl08cd74f.com/*
// @include       *3jmcwio.com/*
// @include       *3rpagb7k11.com/*
// @include       *v746fyw2v.com/*
// @include       *81p5b.top/*
// @include       *8yopdqidj2.com/*
// @include       *aubhiple2.com/*
// @include       *blrqeqn.com/*
// @include       *dlxrlc2ni2.com/*
// @include       *ebahpya.com/*
// @include       *enloe6qtkd.com/*
// @include       *goo2anywhere.com/*
// @include       *hfllrf6lwh.com/*
// @include       *hiekeegi.com/*
// @include       *i9zqq3fj.top/*
// @include       *ilxhsgd.com/*
// @include       *jolic2.com/*
// @include       *jwt8e5vzc1.com/*
// @include       *ka04b.com/*
// @include       *kbzdxt.com/*
// @include       *l4oecosq.com/*
// @include       *lld2q.com/*
// @include       *lzpv4rsmat.com/*
// @include       *mh9dskj8jg.com/*
// @include       *neqbzz4p.top/*
// @include       *pffw8mgd.com/*
// @include       *pl1044.puhtml.com/*
// @include       *pm48j.top/*
// @include       *ptarepjx.com/*
// @include       *putrr6.com/*
// @include       *pw8tq9wk.top/*
// @include       *qpc3hunbn2.com/*
// @include       *rhnw4h506h.com/*
// @include       *rupn6r2g.com/*
// @include       *s2sterra.com/*
// @include       *tbv157xq.com/*
// @include       *terraviewbeat.com/*
// @include       *twk20rw5v1.com/*
// @include       *u4ghzfb.com/*
// @include       *u9oxdnxk8b.com/*
// @include       *under2given.com/*
// @include       *veloqubq.top/*
// @include       *wmjj2vke66.com/*
// @include       *xzipy.com/*
// @include       *ya7easob.top/*
// @include       *ypqy3sgq.com/*
// @include       *yqs6r2hp4j.com/*
// @include       *zbs9uwl4xy.com/*
// @include       *zmjagawa.com/*
// @include       *pl3798.puhtml.com/*
// @include       *zy16eoat1w.com/*
// @include       *ezskz4vee5.com/*
// @include       *v72by5spj.top/*
// @include       *5g65ymza39.com/*
// @include       *8g8y7asx.top/*
// @include       *9utwbj08.top/*
// @include       *cbuy6auv.top/*
// @include       *7rjln8orgh.com/*
// @include       *7vxlfstt.top/*
// @include       *m9in5.top/*
// @include       *pl130610.puhtml.com/*
// @include       *2pxg8bcf.top/*
// @include       *ns3.highcpms.com/*
// @include       *4onqfs7iv4.com/*
// @include       *8wey4x0c.com/*
// @include       *l7xye.top/*
// @include       *q8eqh.top/*
// @include       *seskeu3zk7.com/*
// @include       *0eijh8996i.com/*
// @include       *0sywjs4r1x.com/*
// @include       *79ucic4ss8.com/*
// @include       *95p5qep4aq.com/*
// @include       *pl947.puhtml.com/*
// @include       *hermes.jf71qh5v14.com/*
// @include       *pussl6.com/*
// @include       *hiug862dj0.com/*
// @include       *mka8vaj2ru.com/*
// @include       *8s32e590un.com/*
// @include       *uxbewzrfyp.com/*
// @include       *ebo7v4tkuo.com/*
// @include       *servicos.nlwy0.com/*
// @include       *ahwrin88tl.com/*
// @include       *sloi1.com/*
// @include       *hqzjz7fncd.com/*
// @include       *3t53ambeaq.com/*
// @include       *6fct2uu3vw.com/*
// @include       *86a6b542l7.com/*
// @include       *8v8afxt8lg.com/*
// @include       *9526s7bwd0.com/*
// @include       *9df4mz2kpm.com/*
// @include       *9lhc3x6whk.com/*
// @include       *caxvm62zyz.com/*
// @include       *ckk69drbro.com/*
// @include       *d22chwk8np.com/*
// @include       *d2ergeh3ul.com/*
// @include       *e4w50tqnqk.com/*
// @include       *gfgixev3d4.com/*
// @include       *ig8al3mkou.com/*
// @include       *l9kfxu1c5x.com/*
// @include       *ljja3ef63g.com/*
// @include       *n1g459ky7y.com/*
// @include       *nwcqntzx5i.com/*
// @include       *o1mmijc4ki.com/*
// @include       *pussl8.com/*
// @include       *qiheptnm80.com/*
// @include       *u8vysb7s2v.com/*
// @include       *2cbisyjaae.com/*
// @include       *3e61gdwn1r.com/*
// @include       *vaxaqngzs3.com/*
// @include       *vhldwuv6om.com/*
// @include       *ns3.clickterra.net/*
// @include       *pl105478.puhtml.com/*
// @include       *nlwy0.com/*
// @include       *pl175339.puhtml.com/*
// @include       *pl110767.puhtml.com/*
// @include       *qfdn3gyfbs.com/*
// @include       *3wt4c.com/*
// @include       *newcustomads.com/*
// @include       *pl106970.puhtml.com/*
// @include       *ww1.flashx.co/*
// @include       *.flashx.co/*
// @include       *flashx.co/*
// @include       *ww2.thepiratebay.rocks/*
// @include       *4c7og3qcob.com/*
// @include       *fw5e8yga.top/*
// @include       *k77hof1z7k.com/*
// @include       *loaxuflhen.com/*
// @include       *mtzenhigqg.com/*
// @include       *terravast.com/*
// @include       *ejdkqclkzq.com/*
// @include       *undef8trust.com/*
// @include       *pl2015.puhtml.com/*
// @include       *fkbwtoopwg.com/*
// @include       *gn0gmd9y.top/*
// @include       *ogrz8ii0.top/*
// @include       *reicvfct.top/*
// @include       *0oviy0ub.top/*
// @include       *f5v1x3kgv5.com/*
// @include       *talk4anyone.com/*
// @include       *i62e2b4mfy.com/*
// @include       *1jvd7f7w.top	2018-10-08
// @include       *1gkjk1ms15.com/*
// @include       *urldelivery.com/*
// @include       *dzjv9gbu8a.com/*
// @include       *pl159567.puhtml.com/*
// @include       *pl157084.puhtml.com/*
// @include       *pl3863479.puhtml.com/*
// @include       *ioawyjf4bh.com/*
// @include       *pl130297.puhtml.com/*
// @include       *pl1149.puhtml.com/*
// @include       *s7c66wKh8k.com/*
// @include       *27d6aovb.top/*
// @include       *c52llumx.com/*
// @include       *pl6446637.puhtml.com/*
// @include       *d14emrg9.com/*
// @include       *lie2anyone.com/*
// @include       *newadsclicks.com/*
// @include       *pl12258149.puhtml.com/*
// @include       *pussl42.com/*
// @include       *.pussl42.com/*
// @include       *watchmygirlfriend.tv/*
// @include       *wct.link/*
// @include       *topfreemoney.com/*
// @include       *hajoopteg.com/*
// @include       *.gtarcade.com/*
// @include       *gtarcade.com/*
// @include       *.data1rtb.com/*
// @include       *data1rtb.com/*
// @include       *go.data1rtb.com/*
// @include       *number1victimofcrime.com/*
// @include       *moocauby.com/*
// @include       *goplay4.com/*
// @include       *pybw.gotwidores.info/*
// @include       *.gotwidores.info/*
// @include       *gotwidores.info/*




// @grant       GM_addStyle
// @grant        window.close
// @grant        window.stop
// ==/UserScript==
window.stop();
window.open('location', '_self', '');
window.close();
setTimeout("window.close();", 100);
window.close();
window.open("","_self");
window.close();